# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: install dependencies
      run: go get honnef.co/go/tools/cmd/staticcheck@latest

    - name: Add Go bin to PATH
      run: |
        echo "$HOME/go/bin" >> $GITHUB_PATH  # Add Go bin directory to the PATH so staticcheck can be found

    - name: run staticcheck
      run: staticcheck ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
